use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let resources_dir = manifest_dir.join("resources").join("bytecode");

    println!("cargo:rerun-if-changed={}", resources_dir.display());

    let mut versions = Vec::new();
    if let Ok(entries) = fs::read_dir(&resources_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            if let Some(version) = parse_version(&path) {
                versions.push(version);
            }
        }
    }

    versions.sort_unstable();
    versions.dedup();

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let out_path = out_dir.join("bytecode_formats.rs");
    let mut out_file = fs::File::create(&out_path).expect("create bytecode_formats.rs");

    writeln!(out_file, "// Auto-generated by build.rs. Do not edit.").unwrap();
    writeln!(out_file, "pub fn available_versions() -> &'static [u32] {{").unwrap();
    writeln!(
        out_file,
        "    &[{}]",
        versions
            .iter()
            .map(|v| v.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
    writeln!(out_file, "}}").unwrap();

    writeln!(
        out_file,
        "pub fn format_json_for_version(version: u32) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out_file, "    match version {{").unwrap();
    for version in &versions {
        // Use forward slashes: this string is embedded into an include_str! literal,
        // and a backslash path (from Path::join on Windows) would create invalid
        // escape sequences such as `\b` in the generated source file.
        let rel_path = format!("resources/bytecode/Bytecode{version}.json");
        writeln!(
            out_file,
            "        {version} => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", \"{rel_path}\"))),"
        )
        .unwrap();
    }
    writeln!(out_file, "        _ => None,").unwrap();
    writeln!(out_file, "    }}").unwrap();
    writeln!(out_file, "}}").unwrap();

    // Per-version CallBuiltin index tables, parsed from each Hermes release's
    // Builtins.def (the builtin index ordering is version-specific).
    let builtins_dir = manifest_dir.join("resources").join("builtins");
    println!("cargo:rerun-if-changed={}", builtins_dir.display());
    let mut builtin_versions = Vec::new();
    if let Ok(entries) = fs::read_dir(&builtins_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) != Some("json") {
                continue;
            }
            if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                if let Some(v) = stem
                    .strip_prefix("Builtins")
                    .and_then(|s| s.parse::<u32>().ok())
                {
                    builtin_versions.push(v);
                }
            }
        }
    }
    builtin_versions.sort_unstable();
    builtin_versions.dedup();

    writeln!(
        out_file,
        "pub fn builtins_json_for_version(version: u32) -> Option<&'static str> {{"
    )
    .unwrap();
    writeln!(out_file, "    match version {{").unwrap();
    for version in &builtin_versions {
        let rel_path = format!("resources/builtins/Builtins{version}.json");
        writeln!(
            out_file,
            "        {version} => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", \"{rel_path}\"))),"
        )
        .unwrap();
    }
    writeln!(out_file, "        _ => None,").unwrap();
    writeln!(out_file, "    }}").unwrap();
    writeln!(out_file, "}}").unwrap();

    writeln!(
        out_file,
        "pub fn builtin_table_versions() -> &'static [u32] {{ &[{}] }}",
        builtin_versions
            .iter()
            .map(|v| v.to_string())
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();

    emit_build_fingerprint(&manifest_dir);
}

// Emit a compile-time fingerprint of the decompiler build: its version, every
// source file, and the embedded format and builtin tables. The analysis cache
// keys on this so a rebuilt decompiler never reuses a cache produced by an older
// build. It is computed here, at compile time, so the runtime never has to read
// the executable.
fn emit_build_fingerprint(manifest_dir: &Path) {
    let src_dir = manifest_dir.join("src");
    println!("cargo:rerun-if-changed={}", src_dir.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("Cargo.toml").display()
    );

    let mut hash: u64 = 0xcbf2_9ce4_8422_2325; // FNV-1a 64-bit offset basis
    fnv_update(
        &mut hash,
        env::var("CARGO_PKG_VERSION").unwrap_or_default().as_bytes(),
    );

    let mut files = Vec::new();
    collect_files(&src_dir, "rs", &mut files);
    collect_files(&manifest_dir.join("resources"), "json", &mut files);
    files.sort();
    for f in &files {
        if let Ok(bytes) = fs::read(f) {
            fnv_update(&mut hash, &bytes);
        }
    }

    println!("cargo:rustc-env=DECOMP_BUILD_FINGERPRINT={hash:016x}");
}

fn fnv_update(hash: &mut u64, bytes: &[u8]) {
    for &b in bytes {
        *hash ^= b as u64;
        *hash = hash.wrapping_mul(0x0000_0100_0000_01b3); // FNV-1a 64-bit prime
    }
}

fn collect_files(dir: &Path, ext: &str, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(&path, ext, out);
            } else if path.extension().and_then(|s| s.to_str()) == Some(ext) {
                out.push(path);
            }
        }
    }
}

fn parse_version(path: &Path) -> Option<u32> {
    let file_name = path.file_stem()?.to_str()?;
    if !file_name.starts_with("Bytecode") {
        return None;
    }
    file_name["Bytecode".len()..].parse::<u32>().ok()
}
