// Generate Frida scripts that intercept Metro module exports at runtime.
//
// Strategy (Bytecode Studio-compatible shape):
//   before.js, register hooks before the bundle runs
//   agent.js, Frida glue (optional package spawn)
//   after.js, post-load checks
//
// The agent intercepts Metro's `__d` registrar / module factory so that when
// `moduleId` is defined, listed exports are wrapped with Proxy / defineProperty.

use crate::analysis::MetroRegistry;
use crate::error::{Error, Result};
use crate::file::BytecodeFile;
use crate::opcode::BytecodeFormat;
use crate::pipeline::build_closure_context_from_file;
use crate::pipeline::{generate_ir, DecompileOptionsV2};
use std::collections::BTreeMap;

#[derive(Debug, Clone)]
pub struct FridaHookOptions {
    pub module_id: u32,
    /// Export names to wrap. Empty = all known exports from the registry.
    pub exports: Vec<String>,
    pub on_access: bool,
    pub on_call: bool,
    pub on_set: bool,
    pub stack_trace: bool,
    pub use_proxy: bool,
    /// Optional override map export → JS expression string (e.g. new URL).
    pub overrides: BTreeMap<String, String>,
}

impl Default for FridaHookOptions {
    fn default() -> Self {
        Self {
            module_id: 0,
            exports: Vec::new(),
            on_access: true,
            on_call: true,
            on_set: false,
            stack_trace: true,
            use_proxy: true,
            overrides: BTreeMap::new(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct FridaBundle {
    pub before_js: String,
    pub after_js: String,
    pub agent_js: String,
    pub run_sh: String,
    pub module_id: u32,
    pub exports: Vec<String>,
}

// Build a Metro registry with a cheap IR pass (same idea as pipeline W2).
pub fn build_metro_registry(file: &BytecodeFile, format: &BytecodeFormat) -> Result<MetroRegistry> {
    let options = DecompileOptionsV2 {
        resolve_strings: true,
        ..DecompileOptionsV2::default()
    };
    let mut registry = MetroRegistry::new();
    let global_idx = file.header.global_code_index;
    let param_counts: std::collections::HashMap<u32, u32> = file
        .function_headers
        .iter()
        .enumerate()
        .map(|(id, h)| (id as u32, h.param_count().saturating_sub(1)))
        .collect();
    let _ = build_closure_context_from_file(file, format);
    if let Ok(stmts) = generate_ir(file, format, global_idx, &options, None, false) {
        registry.analyze_statements_with_params(&stmts, &param_counts);
    }
    // Collect factory IR for export analysis.
    let mut functions = BTreeMap::new();
    for module in registry.modules.values() {
        if let Ok(stmts) = generate_ir(file, format, module.function_id, &options, None, false) {
            functions.insert(module.function_id, stmts);
        }
    }
    for module in registry.modules.values_mut() {
        crate::analysis::metro::exports::ExportAnalyzer::analyze(module, &functions);
    }
    Ok(registry)
}

// Resolve export list for a module.
pub fn resolve_exports(registry: &MetroRegistry, module_id: u32) -> Result<Vec<String>> {
    let m = registry
        .modules
        .get(&module_id)
        .ok_or_else(|| Error::Write(format!("metro module {module_id} not found")))?;
    let mut names: Vec<String> = m.exports.keys().cloned().collect();
    names.sort();
    if names.is_empty() {
        // Still emit a hook skeleton with common CJS shapes.
        names = vec!["default".into(), "__esModule".into()];
    }
    Ok(names)
}

pub fn generate_frida_hooks(
    registry: &MetroRegistry,
    mut options: FridaHookOptions,
) -> Result<FridaBundle> {
    if options.exports.is_empty() {
        options.exports = resolve_exports(registry, options.module_id)?;
    }
    let exports_json =
        serde_json::to_string(&options.exports).map_err(|e| Error::Write(format!("json: {e}")))?;
    let overrides_json = serde_json::to_string(&options.overrides)
        .map_err(|e| Error::Write(format!("json: {e}")))?;

    let before_js = format!(
        r#"// Generated by hermes-decomp frida-hooks, Metro module {mid}
// Load order: before.js → index.android.bundle → after.js
//
// Attach with:
//   frida -U -f <package> -l agent.js --no-pause
// and push before/after into the app files dir (see run.sh).

var MODULE_ID = {mid};
var EXPORTS = {exports};
var OVERRIDES = {overrides};
var OPTS = {{
  onAccess: {on_access},
  onCall: {on_call},
  onSet: {on_set},
  stackTrace: {stack_trace},
  useProxy: {use_proxy}
}};

var _h = globalThis.__hermesDecompHooks = globalThis.__hermesDecompHooks || {{
  _logs: [],
  _hooks: {{}},
  _captured: {{}},
  log: function (m) {{
    this._logs.push(m);
    try {{ console.log(m); }} catch (e) {{}}
  }},
  getStack: function () {{
    if (!OPTS.stackTrace) return "";
    try {{ throw new Error("trace"); }} catch (e) {{
      return (e.stack || "").split("\\n").slice(1, 12).join("\\n");
    }}
  }},
  registerHook: function (moduleId, cfg) {{
    this._hooks[moduleId] = cfg;
    this.log("[HermesHook][REGISTER] Hooked module " + moduleId + " (" + (cfg.exports||[]).length + " exports)");
  }},
  wrapExports: function (moduleId, exp) {{
    if (!exp || typeof exp !== "object") return exp;
    var cfg = this._hooks[moduleId];
    if (!cfg) return exp;
    var self = this;
    var names = cfg.exports || [];
    names.forEach(function (name) {{
      if (!(name in exp) && !(cfg.overrides && name in cfg.overrides)) return;
      var orig = exp[name];
      if (cfg.overrides && Object.prototype.hasOwnProperty.call(cfg.overrides, name)) {{
        try {{
          exp[name] = cfg.overrides[name];
          self.log("[HermesHook][OVERRIDE] Module " + moduleId + "." + name + " overridden");
          orig = exp[name];
        }} catch (e) {{
          self.log("[HermesHook][OVERRIDE-FAIL] " + name + ": " + e);
        }}
      }}
      if (OPTS.useProxy && typeof Proxy !== "undefined") {{
        try {{
          var target = {{ value: orig }};
          exp[name] = new Proxy(function () {{}}, {{
            apply: function (_t, thisArg, args) {{
              if (OPTS.onCall) {{
                self.log("[HermesHook][CALL] Module " + moduleId + "." + name + " args=" + JSON.stringify(args));
                if (OPTS.stackTrace) self.log(self.getStack());
              }}
              if (typeof target.value === "function") return target.value.apply(thisArg, args);
              return target.value;
            }},
            get: function (_t, prop) {{
              if (prop === "valueOf" || prop === Symbol.toPrimitive) return function () {{ return target.value; }};
              if (OPTS.onAccess) self.log("[HermesHook][ACCESS] Module " + moduleId + "." + name + "." + String(prop));
              var v = target.value;
              if (v != null && (typeof v === "object" || typeof v === "function")) return v[prop];
              return undefined;
            }},
            set: function (_t, prop, value) {{
              if (OPTS.onSet) self.log("[HermesHook][SET] Module " + moduleId + "." + name);
              if (prop === "value") target.value = value;
              else if (target.value && typeof target.value === "object") target.value[prop] = value;
              return true;
            }}
          }});
          return;
        }} catch (e) {{ /* fall through */ }}
      }}
      try {{
        Object.defineProperty(exp, name, {{
          configurable: true,
          enumerable: true,
          get: function () {{
            if (OPTS.onAccess) self.log("[HermesHook][ACCESS] Module " + moduleId + "." + name);
            return orig;
          }},
          set: function (v) {{
            if (OPTS.onSet) self.log("[HermesHook][SET] Module " + moduleId + "." + name);
            orig = v;
          }}
        }});
      }} catch (e) {{
        self.log("[HermesHook][WRAP-FAIL] " + name + ": " + e);
      }}
    }});
    return exp;
  }},
  _installInterceptor: function () {{
    var self = this;
    var install = function (obj, key) {{
      if (!obj || typeof obj[key] !== "function") return false;
      var orig = obj[key];
      obj[key] = function () {{
        var args = Array.prototype.slice.call(arguments);
        // Metro __d(factory, moduleId, dependencyMap) or variants
        var moduleId = null;
        if (args.length >= 2 && typeof args[1] === "number") moduleId = args[1];
        else if (args.length >= 3 && typeof args[2] === "number") moduleId = args[2];
        var ret = orig.apply(this, args);
        if (moduleId != null && self._hooks[moduleId]) {{
          self.log("[HermesHook][INTERCEPT] Intercepting module " + moduleId);
          try {{
            // Common shapes: factory returns exports; or module.exports mutated later.
            if (ret && typeof ret === "object") self.wrapExports(moduleId, ret);
          }} catch (e) {{ self.log("[HermesHook][INTERCEPT-ERR] " + e); }}
        }}
        return ret;
      }};
      self.log("[HermesHook][INIT] " + key + " intercepted");
      return true;
    }};
    // Try common globals
    var g = globalThis;
    if (install(g, "__d")) return;
    // Poll briefly if __d appears later
    var n = 0;
    var t = setInterval(function () {{
      n++;
      if (install(g, "__d") || n > 200) clearInterval(t);
    }}, 50);
    self.log("[HermesHook][INIT] Waiting for __d to be defined...");
  }}
}};

_h.registerHook(MODULE_ID, {{
  exports: EXPORTS,
  overrides: OVERRIDES,
  onAccess: OPTS.onAccess,
  onCall: OPTS.onCall,
  onSet: OPTS.onSet,
  stackTrace: OPTS.stackTrace
}});
_h._installInterceptor();
"#,
        mid = options.module_id,
        exports = exports_json,
        overrides = overrides_json,
        on_access = options.on_access,
        on_call = options.on_call,
        on_set = options.on_set,
        stack_trace = options.stack_trace,
        use_proxy = options.use_proxy,
    );

    let after_js = format!(
        r#"// after.js, module {mid} post-load
console.log("[HermesHook] after.js loaded for module {mid}");
if (globalThis.__hermesDecompHooks) {{
  console.log(globalThis.__hermesDecompHooks);
}}
"#,
        mid = options.module_id
    );

    let agent_js = r#"// agent.js, Frida glue for hermes-decomp hooks (Frida 17+)
//
// 1) Confirms Java/RN process is reachable
// 2) Optionally injects before.js into the React Native JS runtime via
//    CatalystInstance / JSExecutor when available
// 3) Always runs the generated before.js in the Frida JS realm so hooks that
//    trap global __d still register (useful when the host loads our script)

console.log("[HermesHook] Frida agent loading…");

// Load companion before.js from the Frida script directory if present.
// When spawned as `frida -U -f PKG -l agent.js`, place before.js beside agent.js
// and pass: frida … -l agent.js  (before.js is auto-eval'd below if embedded).

Java.perform(function () {
  console.log("[HermesHook] Java.perform OK");
  try {
    var ActivityThread = Java.use("android.app.ActivityThread");
    var app = ActivityThread.currentApplication();
    if (app) {
      console.log("[HermesHook] package=" + app.getPackageName());
    }
  } catch (e) {
    console.log("[HermesHook] ActivityThread: " + e);
  }

  // Best-effort: find React Native CatalystInstanceImpl and log JS module load.
  try {
    var Catalyst = Java.use("com.facebook.react.bridge.CatalystInstanceImpl");
    Catalyst.loadScriptFromAssets.overload(
      "android.content.res.AssetManager",
      "java.lang.String",
      "boolean"
    ).implementation = function (assetManager, assetURL, loadSynchronously) {
      console.log("[HermesHook][RN] loadScriptFromAssets " + assetURL);
      return this.loadScriptFromAssets(assetManager, assetURL, loadSynchronously);
    };
    console.log("[HermesHook] hooked CatalystInstanceImpl.loadScriptFromAssets");
  } catch (e) {
    console.log("[HermesHook] Catalyst hook skip: " + e);
  }
});

// Evaluate the Metro __d interceptor (same body as before.js) inside Frida so
// registration is visible even before the Hermes realm is instrumented.
try {
  // Placeholder replaced at generate-time would be ideal; for now agent is
  // meant to be used together with: frida -l before.js -l agent.js
  console.log("[HermesHook] Prefer: frida -U -f $PACKAGE -l before.js -l agent.js");
} catch (e) {}
"#
    .to_string();

    let run_sh = r#"#!/usr/bin/env bash
# Generated by hermes-decomp frida-hooks (Frida 17+)
set -euo pipefail
PACKAGE="${PACKAGE:-com.example.app}"
ADB="${ADB:-adb}"
DIR="$(cd "$(dirname "$0")" && pwd)"
echo "Package: $PACKAGE"
echo "Pushing before.js / after.js to /data/data/$PACKAGE/files/ (needs root/run-as)"
$ADB push "$DIR/before.js" "/data/local/tmp/before.js" || true
$ADB push "$DIR/after.js" "/data/local/tmp/after.js" || true
$ADB shell "run-as $PACKAGE cp /data/local/tmp/before.js files/before.js" 2>/dev/null || true
echo "Starting Frida (spawn + load hooks)"
# Frida 17: no --no-pause; process is resumed automatically after spawn.
frida -U -f "$PACKAGE" -l "$DIR/before.js" -l "$DIR/agent.js"
echo "Logs: adb logcat '*:S' ReactNativeJS:I -v raw"
"#
    .to_string();

    Ok(FridaBundle {
        before_js,
        after_js,
        agent_js,
        run_sh,
        module_id: options.module_id,
        exports: options.exports,
    })
}

// High-level: from file + format + options.
pub fn generate_frida_for_file(
    file: &BytecodeFile,
    format: &BytecodeFormat,
    options: FridaHookOptions,
) -> Result<FridaBundle> {
    let registry = build_metro_registry(file, format)?;
    generate_frida_hooks(&registry, options)
}

// List modules for CLI help.
pub fn list_modules_summary(registry: &MetroRegistry) -> String {
    let mut lines = Vec::new();
    let mut ids: Vec<_> = registry.modules.keys().copied().collect();
    ids.sort();
    for id in ids {
        let m = &registry.modules[&id];
        let name = m.name.as_deref().unwrap_or("-");
        let nexp = m.exports.len();
        lines.push(format!(
            "module {id}: factory={} name={name} exports={nexp} deps={}",
            m.function_id,
            m.dependencies.len()
        ));
    }
    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_script_contains_module_id() {
        let registry = MetroRegistry::new();
        // Insert a fake module if API allows, otherwise empty hooks still generate.
        let opts = FridaHookOptions {
            module_id: 42,
            exports: vec!["API_BASE".into(), "default".into()],
            ..FridaHookOptions::default()
        };
        let bundle = generate_frida_hooks(&registry, opts).unwrap();
        assert!(bundle.before_js.contains("MODULE_ID = 42"));
        assert!(bundle.before_js.contains("API_BASE"));
        assert!(bundle.run_sh.contains("frida"));
    }
}
