pub mod detection;
pub mod exports;
mod graph;
mod propagation;
pub mod registry;

// Generic name prefixes that should not be used as module names.
// These are generated by the decompiler and do not carry semantic meaning.
pub(crate) const GENERIC_NAME_PREFIXES: &[&str] = &[
    "tmp", "closure_", "fnResult", "arg", "module_",
    "_interopRequire", "_interopDefault", "_interopNamespace",
    // Metro factory role names get a `_` prefix when they collide with a
    // builtin/reserved word during register naming, and are deduped to
    // `_module`, `_module1`, `_exports2`, …, none are real module names.
    "_module", "_exports", "_require", "_global", "_dependencyMap",
    "_importDefault", "_importAll",
];

// Exact generic names that should not be used as module names.
pub(crate) const GENERIC_EXACT_NAMES: &[&str] = &[
    "default", "_default", "undefined", "null", "true", "false",
    "item", "self", "key", "value", "merged",
    "exports", "wrapper", "require", "anonymous", "global",
    "__esModule", "module", "dependencyMap",
    // React Native codegen gives every native component the same export key,
    // holding the view config. `infer_name_from_view_config` reads the real
    // component name out of it instead.
    "__INTERNAL_VIEW_CONFIG",
    // Metro factory parameter role names (and their reserved-word-escaped
    // `_`-prefixed forms) must never be mistaken for a module's own name.
    "_module", "_exports", "_require", "_global", "_dependencyMap",
    "importDefault", "importAll", "_importDefault", "_importAll",
    "Object", "Object2", "Object3", "Array", "Array2", "Array3",
    "num", "str", "val", "res",
    // Names the decompiler synthesizes for unnamed registers (see
    // `transforms::var_naming::suggestions`). They describe what a value came
    // from, never what the module is.
    "items", "keys", "values", "entries", "result", "results", "prototype",
    "call", "apply", "toString", "arr", "obj", "fn",
    // Common method / export keys that leaked as Metro specifiers
    // (`from "clear"`, `export * from "keys"`). These are not recovered names.
    "clear", "store", "callback", "set",
];

// Helper functions the transpiler injects into every module that needs them, so
// each copy carries the same name. A bundle has hundreds of identical
// `_getRequireWildcardCache` / `_callSuper` definitions, and a hoisted helper is
// often the first function in a factory body, which makes these by far the most
// common wrong module name in a large bundle.
pub(crate) const TRANSPILER_HELPER_NAMES: &[&str] = &[
    // Babel: module interop
    "_getRequireWildcardCache", "ownKeys",
    // Babel: classes
    "_typeof", "_classCallCheck", "_defineProperties", "_createClass",
    "_callSuper", "_createSuper", "_inherits", "_inheritsLoose",
    "_possibleConstructorReturn", "_assertThisInitialized",
    "_isNativeReflectConstruct", "_isNativeFunction", "_getPrototypeOf",
    "_setPrototypeOf", "_superPropBase", "_superPropGet", "_wrapNativeSuper",
    "_construct", "_newArrowCheck", "_instanceof", "_readOnlyError",
    "_writeOnlyError", "_applyDecoratedDescriptor", "_initializerDefineProperty",
    "_classPrivateFieldGet", "_classPrivateFieldSet", "_classPrivateMethodGet",
    // Babel: spread / destructuring
    "_toConsumableArray", "_arrayWithoutHoles", "_iterableToArray",
    "_unsupportedIterableToArray", "_nonIterableSpread", "_arrayLikeToArray",
    "_slicedToArray", "_arrayWithHoles", "_iterableToArrayLimit",
    "_nonIterableRest", "_createForOfIteratorHelper",
    "_createForOfIteratorHelperLoose", "_objectSpread", "_objectSpread2",
    "_defineProperty", "_objectWithoutProperties",
    "_objectWithoutPropertiesLoose", "_extends", "_toPrimitive",
    "_toPropertyKey", "_taggedTemplateLiteral", "_taggedTemplateLiteralLoose",
    // Babel: async / generators
    "_asyncToGenerator", "_asyncIterator", "_awaitAsyncGenerator",
    "_wrapAsyncGenerator", "_asyncGeneratorDelegate", "_skipFirstGeneratorNext",
    "_regeneratorRuntime", "_regenerator", "_usingCtx",
    // graphql-tag: every generated document module defines this deduper
    "_unique",
    // TypeScript (tslib)
    "__importDefault", "__importStar", "__awaiter", "__generator", "__extends",
    "__assign", "__rest", "__decorate", "__param", "__metadata",
    "__spreadArray", "__spread", "__spreadArrays", "__values", "__read",
    "__exportStar", "__createBinding", "__makeTemplateObject", "__await",
    "__asyncValues", "__asyncGenerator", "__asyncDelegator",
    "__classPrivateFieldGet", "__classPrivateFieldSet",
];

// Extra placeholders rejected as import specifiers even when they can still be
// a meaningful *binding* in other passes. `size` is the next export on Discord
// module 2 after `clear`; `index` is the stem of many `index.tsx` files.
const SPECIFIER_PLACEHOLDERS: &[&str] = &["size", "index"];

// How many modules may share one recovered stem before the stem is treated as a
// shared helper/export name rather than a module identity. Genuinely repeated
// filenames in a bundle (two `Dispatcher.tsx` in different packages) come in
// small groups and stay disambiguated; a call target reused by hundreds of
// modules does not.
const MAX_MODULES_PER_STEM: usize = 4;

// True when `name` is the honest fallback specifier `module_<id>`, not a recovered
// name. Codegen still emits it; naming must not treat it as ground truth.
pub(crate) fn is_module_id_fallback(name: &str) -> bool {
    name.strip_prefix("module_")
        .is_some_and(|rest| !rest.is_empty() && rest.bytes().all(|b| b.is_ascii_digit()))
}

// True when `name` must not be stored or emitted as a recovered module specifier.
pub(crate) fn is_generic_module_specifier(name: &str) -> bool {
    if is_module_id_fallback(name) {
        return true;
    }
    if is_obviously_generic(name) {
        return true;
    }
    SPECIFIER_PLACEHOLDERS.contains(&name)
}

// True when `name` may appear in `from "..."` / import_map. The `module_N`
// fallback is allowed here so lookup does not drop unnamed dependencies.
pub(crate) fn is_usable_module_specifier(name: &str) -> bool {
    is_module_id_fallback(name) || !is_generic_module_specifier(name)
}

// After every naming pass: drop placeholder specifiers and make each recovered
// name unique across module ids. `locked` are modules named from ground truth
// (fileFinishedImporting / source-file encoding): they keep the bare stem when
// a later heuristic collides. Two Metro ids never share a specifier.
//
// When several modules share a stem and we have their `fileFinishedImporting`
// paths, disambiguate with parent directories (`flux/Dispatcher` vs
// `Dispatcher.tsx` → `Dispatcher`) instead of the volatile Metro id
// (`Dispatcher_709`), so a require is grep-able against the source filename.
pub(crate) fn finalize_module_specifiers(
    registry: &mut MetroRegistry,
    locked: &std::collections::HashSet<u32>,
    gt_paths: &std::collections::HashMap<u32, String>,
) {
    use std::collections::{BTreeMap, HashSet};

    for (id, module) in registry.modules.iter_mut() {
        let Some(name) = &module.name else { continue };
        if is_generic_module_specifier(name) {
            module.name = None;
            continue;
        }
        // A recovered name that describes an action names one of the module's
        // functions, not the module. Several passes reach a module through a
        // single export they managed to see (`exports.getAndroidId = ...`) and
        // hand that key to the whole module, so captures of expo-application
        // printed `getAndroidId.nativeApplicationVersion`, naming a function and
        // asking it for a field it does not have. Ground truth names keep their
        // stem; a guessed one goes back to the honest id.
        if !locked.contains(id) && names_an_action(name) {
            module.name = None;
        }
    }

    let mut by_name: BTreeMap<String, Vec<u32>> = BTreeMap::new();
    for (id, module) in &registry.modules {
        if let Some(name) = &module.name {
            by_name.entry(name.clone()).or_default().push(*id);
        }
    }

    let mut occupied: HashSet<String> = by_name.keys().cloned().collect();
    let mut renames: Vec<(u32, String)> = Vec::new();
    let mut clears: Vec<u32> = Vec::new();
    for (name, mut ids) in by_name {
        if ids.len() <= 1 {
            continue;
        }
        ids.sort_unstable();
        // A stem claimed by this many modules is not any one module's identity:
        // it is a helper they all call (`registerAsset` in every packaged asset
        // module) or an export key they all re-expose (`formatDistance` in every
        // date-fns locale). Numbering them `registerAsset_1240`,
        // `registerAsset_1241`, ... invents thousands of false specifiers that
        // also change whenever Metro renumbers, so the stem is dropped and those
        // modules fall back to the stable `module_<content_hash>`. A module whose
        // name came from ground truth keeps it.
        if ids.len() > MAX_MODULES_PER_STEM {
            clears.extend(ids.iter().copied().filter(|id| !locked.contains(id)));
            continue;
        }
        let winner = pick_specifier_winner(&ids, locked, gt_paths);
        for &id in &ids {
            if id == winner {
                continue;
            }
            let mut cand = None;
            if let Some(path) = gt_paths.get(&id) {
                for next in path_disambiguators(path, &name) {
                    if !occupied.contains(&next) && !is_generic_module_specifier(&next) {
                        cand = Some(next);
                        break;
                    }
                }
            }
            // No source path to disambiguate with: we cannot tell which module
            // owns the stem, so nothing is invented. `{name}_{id}` would read as
            // a recovered name while really encoding a Metro id that changes on
            // every build. The module goes back to unnamed and picks up the
            // stable `module_<content_hash>` instead.
            let Some(cand) = cand else {
                clears.push(id);
                continue;
            };
            occupied.insert(cand.clone());
            renames.push((id, cand));
        }
    }
    for (id, new_name) in renames {
        if let Some(module) = registry.modules.get_mut(&id) {
            module.name = Some(new_name);
        }
    }
    for id in clears {
        if let Some(module) = registry.modules.get_mut(&id) {
            module.name = None;
        }
    }

    for (func_id, factory) in registry.factories.iter_mut() {
        if let Some(mod_id) = registry.function_to_module.get(func_id).copied() {
            if let Some(module) = registry.modules.get(&mod_id) {
                factory.name = module.name.clone();
            }
        }
    }
}

// Prefer the module whose source path is the shortest (a bare `Dispatcher.tsx`
// beats `packages/flux/Dispatcher.tsx`), then a locked GT name, then the
// lowest Metro id. The shortest path is the file the app actually named
// `Dispatcher.tsx`; nested copies keep a parent-dir prefix.
fn pick_specifier_winner(
    ids: &[u32],
    locked: &std::collections::HashSet<u32>,
    gt_paths: &std::collections::HashMap<u32, String>,
) -> u32 {
    *ids
        .iter()
        .min_by_key(|id| {
            let segs = gt_paths
                .get(id)
                .map(|p| meaningful_path_segments(p).len().max(1))
                .unwrap_or(1);
            let unlocked = u32::from(!locked.contains(id));
            (segs, unlocked, **id)
        })
        .unwrap_or(&ids[0])
}

// Directory names that do not distinguish two files of the same stem.
const GENERIC_PATH_SEGS: &[&str] = &[
    "js", "ts", "src", "lib", "packages", "node_modules", "native", "ios", "android", "web",
];

fn strip_source_file_ext(file: &str) -> &str {
    let mut stem = file
        .strip_suffix(".tsx")
        .or_else(|| file.strip_suffix(".ts"))
        .or_else(|| file.strip_suffix(".jsx"))
        .or_else(|| file.strip_suffix(".js"))
        .unwrap_or(file);
    for plat in [".android", ".native", ".ios", ".web"] {
        if let Some(stripped) = stem.strip_suffix(plat) {
            stem = stripped;
            break;
        }
    }
    stem
}

fn meaningful_path_segments(path: &str) -> Vec<String> {
    let path = path.split(['?', '#']).next().unwrap_or(path);
    path.split('/')
        .filter(|s| !s.is_empty() && *s != "." && *s != "..")
        .map(|s| strip_source_file_ext(s).to_string())
        .filter(|s| {
            !s.is_empty()
                && !GENERIC_PATH_SEGS.contains(&s.as_str())
                && crate::util::is_valid_identifier(s)
        })
        .collect()
}

// Increasingly specific suffixes of the GT path: `flux/Dispatcher`, then
// `discord_common/flux/Dispatcher`, … Never emits the bare stem (that is the
// winner's specifier).
fn path_disambiguators(path: &str, stem: &str) -> Vec<String> {
    let mut segs = meaningful_path_segments(path);
    if segs.last().map(String::as_str) != Some(stem) {
        segs.push(stem.to_string());
    }
    let mut out = Vec::new();
    for n in 2..=segs.len() {
        let cand = segs[segs.len() - n..].join("/");
        if cand != stem {
            out.push(cand);
        }
    }
    out
}

// Check if a name is obviously generic (decompiler-generated, too vague, or a common placeholder).
//
// This is the shared core used by both `detection::is_meaningful_name()` and
// `propagation::is_meaningful_require_name()`. Each caller adds its own
// additional checks (e.g., `f1234` pattern, register patterns, length checks).
pub(crate) fn is_obviously_generic(name: &str) -> bool {
    // A module name becomes a file name and an import specifier, so anything
    // that is not one token cannot be one (`get registerCallableModule` is an
    // accessor key picked up from a barrel module's property table).
    if name.chars().any(char::is_whitespace) { return true; }
    if is_generic_ident(name) { return true; }
    // Colliding names get a numeric suffix during register naming (`keys1`,
    // `_default2`, `fnResult3`), so judge those by the name they were made from.
    let base = name.trim_end_matches(|c: char| c.is_ascii_digit());
    base != name && !base.is_empty() && is_generic_ident(base)
}

fn is_generic_ident(name: &str) -> bool {
    // Reject exact matches from shared list
    if GENERIC_EXACT_NAMES.contains(&name) { return true; }
    // Reject transpiler-injected helpers, which every module redefines
    if TRANSPILER_HELPER_NAMES.contains(&name) { return true; }
    // Reject generic prefixes from shared list
    if GENERIC_NAME_PREFIXES.iter().any(|p| name.starts_with(p)) { return true; }
    // Reject decompiler-generated *Result names (fnResult, fn2Result,
    // definePropertyResult, etc.). The register namer also numbers repeats, so
    // trailing digits are stripped first: `importDefaultResult1` is the same
    // temporary as `importDefaultResult` and must not become a module name.
    if name.trim_end_matches(|c: char| c.is_ascii_digit()).ends_with("Result") { return true; }
    // Reject register or type role names with an optional numeric suffix, for any
    // number of digits: obj, obj2, obj129, arr5, items9, set7, fn3, num2, str1.
    // The suffix count is unbounded since same-role registers are numbered without
    // a cap, so a fixed length check (obj up to obj99) let obj129 slip through and
    // leak as a module name. A real word keeps its non-digit tail (object, arrow,
    // items list keys, settings) and is not rejected.
    if is_role_name_with_digits(name) { return true; }
    false
}

// True when `name` is a register/type role base followed by nothing or only
// digits (`obj`, `arr129`), the shape the register namer produces for anonymous
// values. A base followed by letters (`object`, `arrow`, `settings`) is a real
// name and returns false.
fn is_role_name_with_digits(name: &str) -> bool {
    const ROLE_BASES: &[&str] = &[
        "obj", "arr", "items", "item", "set", "list", "map",
        "fn", "num", "str", "val", "bool", "res", "el",
    ];
    for base in ROLE_BASES {
        if let Some(rest) = name.strip_prefix(base) {
            if rest.is_empty() || rest.bytes().all(|b| b.is_ascii_digit()) {
                return true;
            }
        }
    }
    false
}

#[cfg(test)]
mod generic_name_tests {
    use super::is_obviously_generic;

    #[test]
    fn transpiler_helpers_never_name_a_module() {
        // Every module using `import * as ns` redefines this one, and it is
        // hoisted to the top of the factory where name inference looks first.
        for name in [
            "_getRequireWildcardCache",
            "_callSuper",
            "_typeof",
            "_classCallCheck",
            "_toConsumableArray",
            "__importStar",
            "__awaiter",
            // graphql-tag emits this in every generated document module
            "_unique",
        ] {
            assert!(is_obviously_generic(name), "{name} should be rejected");
        }
    }

    #[test]
    fn framework_protocol_keys_are_not_names() {
        // Every RN codegen'd native component exports this same key.
        assert!(is_obviously_generic("__INTERNAL_VIEW_CONFIG"));
    }

    #[test]
    fn numeric_suffix_does_not_launder_a_generic_name() {
        for name in ["keys1", "_default2", "result10", "self2", "fnResult3"] {
            assert!(is_obviously_generic(name), "{name} should be rejected");
        }
        // Only the base name decides: a real name that ends in a digit stays.
        for name in ["Base64", "Sha256", "H264", "S3Client"] {
            assert!(!is_obviously_generic(name), "{name} should be kept");
        }
    }

    #[test]
    fn multi_token_names_are_rejected() {
        // Accessor keys from a barrel's property table, never a module name.
        assert!(is_obviously_generic("get registerCallableModule"));
        assert!(is_obviously_generic("set FlatList"));
    }

    #[test]
    fn real_module_names_survive() {
        for name in [
            "AccessibilityInfo",
            "UIManager",
            "PlatformConstants",
            "keyExtractor",
            "useSections",
            "RNCSafeAreaProvider",
        ] {
            assert!(!is_obviously_generic(name), "{name} should be kept");
        }
    }
}

pub use detection::MetroDetector;
pub use graph::{DependencyGraph, DependencyTree};
pub use propagation::{propagate_module_names, rewrite_dependency_maps_late};
pub(crate) use propagation::propagate_module_names_to_closures;
pub use registry::{FactoryRoles, MetroModule, MetroRegistry};

// Helper to expose analyze as a static method on MetroRegistry for compatibility
impl MetroRegistry {
    pub fn analyze(statements: &[crate::ir::Statement]) -> Self {
        let mut registry = Self::new();
        MetroDetector::analyze_statements(statements, &mut registry, &std::collections::HashMap::new());
        registry
    }

    pub fn analyze_statements(&mut self, statements: &[crate::ir::Statement]) {
        MetroDetector::analyze_statements(statements, self, &std::collections::HashMap::new());
    }

    // Variant that supplies factory parameter counts (function_id -> declared
    // param count, this-excluded) so module roles match the Metro convention.
    pub fn analyze_statements_with_params(
        &mut self,
        statements: &[crate::ir::Statement],
        param_counts: &std::collections::HashMap<u32, u32>,
    ) {
        MetroDetector::analyze_statements(statements, self, param_counts);
    }
}

// Re-expose Graph methods on Registry for compatibility if needed,
// OR refactor callers to use DependencyGraph directly.
// For now, let's keep the extension methods or just use the new API.
// To match original API:
impl MetroRegistry {
    pub fn get_dependency_tree(&self, module_id: u32, max_depth: usize) -> DependencyTree {
        DependencyGraph::get_dependency_tree(self, module_id, max_depth)
    }
}

#[cfg(test)]
mod generic_specifier_tests {
    use super::is_obviously_generic;
    #[test]
    fn rejects_role_names_with_any_digit_count() {
        for n in ["obj", "obj2", "obj129", "items9", "set7", "arr12", "fn3", "num2", "str1", "val0", "map", "list5", "res4"] {
            assert!(is_obviously_generic(n), "{n} should be generic");
        }
    }
    #[test]
    fn keeps_real_words() {
        for n in ["object", "objectPool", "arrow", "settings", "mapper", "response", "listener", "items_list", "numbers", "string2Value"] {
            assert!(!is_obviously_generic(n), "{n} should be kept");
        }
    }

    #[test]
    fn rejects_placeholder_module_specifiers() {
        use super::{finalize_module_specifiers, is_generic_module_specifier, is_usable_module_specifier};
        use super::registry::{FactoryRoles, MetroModule, MetroRegistry};

        for n in ["clear", "keys", "result", "store", "callback", "set", "size", "index", "obj2", "module_2"] {
            assert!(is_generic_module_specifier(n), "{n} should be a generic specifier");
            assert!(!is_usable_module_specifier(n) || n == "module_2", "{n} usable?");
        }
        assert!(is_usable_module_specifier("module_2"));
        assert!(is_usable_module_specifier("LoggerPIIRestrictedObjects"));
        assert!(!is_generic_module_specifier("LoggerPIIRestrictedObjects"));

        let mut registry = MetroRegistry::new();
        let mk = |id: u32, name: Option<&str>| MetroModule {
            module_id: id,
            function_id: id,
            name: name.map(str::to_string),
            dependencies: Vec::new(),
            exports: Default::default(),
            roles: FactoryRoles::standard(),
        };
        registry.modules.insert(2, mk(2, Some("clear")));
        registry.modules.insert(6, mk(6, Some("LoggerPIIRestrictedObjects")));
        registry.modules.insert(10, mk(10, Some("SnowflakeUtils")));
        registry.modules.insert(11, mk(11, Some("SnowflakeUtils")));
        registry.modules.insert(12, mk(12, Some("keys")));
        finalize_module_specifiers(&mut registry, &Default::default(), &Default::default());
        assert_eq!(registry.modules[&2].name, None);
        assert_eq!(registry.modules[&6].name.as_deref(), Some("LoggerPIIRestrictedObjects"));
        assert_eq!(registry.modules[&10].name.as_deref(), Some("SnowflakeUtils"));
        // The second claimant has no source path to disambiguate with, so no name
        // is invented for it: it goes back to unnamed rather than becoming
        // `SnowflakeUtils_11`, which would encode a Metro id as a recovered name.
        assert_eq!(registry.modules[&11].name, None);
        assert_eq!(registry.modules[&12].name, None);

        let mut registry = MetroRegistry::new();
        registry.modules.insert(3, mk(3, Some("Logger")));
        registry.modules.insert(6, mk(6, Some("Logger")));
        let locked = std::collections::HashSet::from([6u32]);
        finalize_module_specifiers(&mut registry, &locked, &Default::default());
        assert_eq!(registry.modules[&6].name.as_deref(), Some("Logger"));
        assert_eq!(registry.modules[&3].name, None);
    }

    #[test]
    fn drops_stems_shared_by_many_modules() {
        use super::{finalize_module_specifiers, is_obviously_generic};
        use super::registry::{FactoryRoles, MetroModule, MetroRegistry};

        // A numbered decompiler temporary is not a module name. `Result` alone was
        // already rejected; the numbered repeats leaked through and named modules
        // `importDefaultResult1`, which then collided across the whole bundle.
        assert!(is_obviously_generic("importDefaultResult"));
        assert!(is_obviously_generic("importDefaultResult1"));
        assert!(is_obviously_generic("SymbolResult12"));
        assert!(!is_obviously_generic("QueryResultView"));

        let mk = |id: u32, name: &str| MetroModule {
            module_id: id,
            function_id: id,
            name: Some(name.to_string()),
            dependencies: Vec::new(),
            exports: Default::default(),
            roles: FactoryRoles::standard(),
        };

        // Every packaged asset module calls `registerAsset`, so the stem names none
        // of them. With more claimants than MAX_MODULES_PER_STEM the stem is dropped
        // for all of them instead of numbering them `registerAsset_<metro id>`.
        let mut registry = MetroRegistry::new();
        let shared: Vec<u32> = (1..=(super::MAX_MODULES_PER_STEM as u32 + 2)).collect();
        for &id in &shared {
            registry.modules.insert(id, mk(id, "registerAsset"));
        }
        registry.modules.insert(100, mk(100, "Dispatcher"));
        registry.modules.insert(101, mk(101, "Dispatcher"));
        finalize_module_specifiers(&mut registry, &Default::default(), &Default::default());
        for &id in &shared {
            assert_eq!(registry.modules[&id].name, None, "module {id} kept a shared stem");
        }
        // A small group is not a shared helper: the winner still keeps the stem.
        assert_eq!(registry.modules[&100].name.as_deref(), Some("Dispatcher"));
        assert_eq!(registry.modules[&101].name, None);

        // Ground truth outranks the shared-stem rule.
        let mut registry = MetroRegistry::new();
        for &id in &shared {
            registry.modules.insert(id, mk(id, "registerAsset"));
        }
        let locked = std::collections::HashSet::from([shared[0]]);
        finalize_module_specifiers(&mut registry, &locked, &Default::default());
        assert_eq!(registry.modules[&shared[0]].name.as_deref(), Some("registerAsset"));
        assert_eq!(registry.modules[&shared[1]].name, None);
    }

    #[test]
    fn uniquifies_colliding_stems_from_source_path() {
        use super::{finalize_module_specifiers, path_disambiguators};
        use super::registry::{FactoryRoles, MetroModule, MetroRegistry};
        use std::collections::{HashMap, HashSet};

        assert_eq!(
            path_disambiguators(
                "../discord_common/js/packages/flux/Dispatcher.tsx",
                "Dispatcher"
            ),
            vec!["flux/Dispatcher".to_string(), "discord_common/flux/Dispatcher".to_string()]
        );
        assert!(path_disambiguators("Dispatcher.tsx", "Dispatcher").is_empty());

        let mk = |id: u32, name: Option<&str>| MetroModule {
            module_id: id,
            function_id: id,
            name: name.map(str::to_string),
            dependencies: Vec::new(),
            exports: Default::default(),
            roles: FactoryRoles::standard(),
        };
        let mut registry = MetroRegistry::new();
        registry.modules.insert(650, mk(650, Some("Dispatcher")));
        registry.modules.insert(709, mk(709, Some("Dispatcher")));
        let locked = HashSet::from([650u32, 709]);
        let paths = HashMap::from([
            (650u32, "../discord_common/js/packages/flux/Dispatcher.tsx".to_string()),
            (709u32, "Dispatcher.tsx".to_string()),
        ]);
        finalize_module_specifiers(&mut registry, &locked, &paths);
        assert_eq!(registry.modules[&709].name.as_deref(), Some("Dispatcher"));
        assert_eq!(registry.modules[&650].name.as_deref(), Some("flux/Dispatcher"));
    }
}

// Whether a name describes an action rather than a thing. Such a name belongs to
// a function, never to the module holding it, so a module must not be named after
// an export called this.
//
// A module is named from the exports the analysis recovered, not from everything
// it exports. expo-application arrived here with `getAndroidId` recovered and the
// rest missed, so the whole module took that name and captures of it printed
// `getAndroidId.nativeApplicationVersion`, naming a function and asking it for a
// field it does not have. A verb led name is the reliable signal that what was
// recovered is a function, so the module keeps its honest id instead.
pub(crate) fn names_an_action(name: &str) -> bool {
    const VERBS: &[&str] = &[
        "get", "set", "is", "has", "use", "add", "on", "create", "make", "fetch",
        "load", "save", "read", "write", "parse", "format", "handle", "remove",
        "delete", "clear", "reset", "update", "init", "build", "check", "ensure",
        "with", "to", "from", "can", "should", "will", "did",
    ];
    VERBS.iter().any(|verb| {
        name.strip_prefix(verb)
            .and_then(|rest| rest.chars().next())
            .is_some_and(|c| c.is_ascii_uppercase())
    })
}
